### ISSUE TITLE
MACHINENAME wrong when cross-building

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#2]
In a cross-build environment, CMakeList still runs `uname -m` to find out the compile flags.  Provide an option to override the MACHINENAME or detect CMAKE_CROSSCOMPILING / CMAKE_C_COMPILER_TARGET.

**Comment by niklata** [comment]
I've added a CROSSCOMPILE_MACHINENAME environment variable that will disable machine detection and allow the MACHINENAME to be manually set.

I'm not sure if this is the best way, but CMAKE_C_COMPILER_TARGET seems to be poorly documented, and I assume CMAKE_CROSSCOMPILING is just a binary flag.  The CMake documentation isn't all that good and searches are not too helpful.

If there's a better way, please let me know and I'll be more than happy to change from this approach.

**Comment by leahneukirchen** [comment]
This works, but ncmlib has the same issue.

**Comment by niklata** [comment]
ncmlib should be updated similarly now.

It shouldn't have the try_run-related issue for glibc detection, either, since it never relied on that feature.
