### ISSUE TITLE
"Still looking for DHCP server hardware address" when using proxy-DHCP

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#3]
I'm on a network which uses DHCP proxying, thus the DHCP server is not on the same level-2 network and cannot be arppinged.

```
ndhc: ndhc client 1.5 started on interface [wlan0].
ndhc: wlan0: Discovering DHCP servers...
ndhc: wlan0: Received an offer of 10.181.15.152 from server 10.156.33.139.
ndhc: wlan0: Sending a selection request for 10.181.15.152...
ndhc: wlan0: UDP length [576] does not match header length field [328].
ndhc: wlan0: Sending a selection request for 10.181.15.152...
ndhc: wlan0: UDP length [576] does not match header length field [328].
ndhc: wlan0: Sending a selection request for 10.181.15.152...
ndhc: wlan0: Received a DHCP ACK with an unexpected server id: 10.156.33.138.  Ignoring it.
ndhc: wlan0: Accepted a firm offer for 10.181.15.152.  Validating...
ndhc: wlan0: arp: Probing for hosts that may conflict with our lease...
ndhc: wlan0: arp: Probing for hosts that may conflict with our lease...
ndhc: wlan0: Lease of 10.181.15.152 obtained.  Lease time is 2400 seconds.
ndhc: wlan0: Sent to ifchd: 'ip4:10.181.15.152,255.255.240.0,10.181.15.255;routr:10.181.15.254;dns:10.156.33.53,129.187.5.1;dom:eduroam.mwn.de;'
ndhc: wlan0: arp: Searching for dhcp server and gw addresses...
ndhc: wlan0: Interface IP, subnet, and broadcast were already OK.
ndhc: wlan0: Gateway router set to: '10.181.15.254'
ndhc: Added DNS server: '10.156.33.53,129.187.5.1'
ndhc: wlan0: arp: Gateway hardware address d8:67:d9:6e:9b:42
ndhc: Added DNS domain: 'eduroam.mwn.de'
ndhc: wlan0: Commands received and successfully executed.
ndhc: wlan0: arp: Still looking for DHCP server hardware address...
ndhc: wlan0: arp: Still looking for DHCP server hardware address...
ndhc: wlan0: arp: Still looking for DHCP server hardware address...
```

ndhc will look for eternity to get the DHCP server hardware address, but the server is in a different segment:

```
% tracepath 10.156.33.138 -n
 1?: [LOCALHOST]                                         pmtu 1500
 1:  10.181.15.254                                        16.662ms 
 1:  10.181.15.254                                        17.455ms 
 2:  129.187.0.137                                         7.956ms 
 3:  10.156.33.138                                         2.882ms reached
     Resume: pmtu 1500 hops 3 back 62 
```

I'm not sure what having "got_server_arp" is actually good for.

**Comment by leahneukirchen** [comment]
After some time, this goes on as

```
2015-02-12T20:56:56.66492 user.notice: ndhc: wlan0: Sending a renew request...
2015-02-12T20:57:01.66672 user.notice: ndhc: wlan0: arp: Still looking for DHCP server hardware address...
2015-02-12T20:57:01.66686 user.notice: ndhc: wlan0: Sending a renew request...
2015-02-12T20:57:06.67118 user.notice: ndhc: wlan0: arp: Still looking for DHCP server hardware address...
```

**Comment by niklata** [comment]
The arp queries are for fingerprinting the network in order to detect whether the machine has been moved to a different network.  If the link state is lost and regained while still within the lease time, and the machine hasn't changed networks, then ndhc doesn't need to do anything.  This can be useful for mobile machines.

However, I hadn't considered the case of DHCP proxies; all of my normal networks are simple and have the DHCP server on the same segment.  This error should certainly not be fatal and should instead just force ndhc to fall back to the conservative approach of attempting to renew the existing lease on link loss/gain.

I will fix this issue.

**Comment by niklata** [comment]
I've just committed a changeset that should make ndhc give up after two attempts at fingerprinting the DHCP server.  It will then just rely on the gateway address for fingerprinting.

It might be possible to instead collect the DHCP relay agent IP address (via the socket peer address) and fingerprint against it, but that's a lot more work and not so easy to do without a local test environment.  However, this approach should be robust, and fingerprinting is definitely a luxury.

Please let me know if everything works with this change.  I'll leave the bug open for now.

**Comment by niklata** [comment]
I wasn't happy with weakening the fingerprinting, so after thinking a bit I made another commit that should make ndhc fingerprint the relay agent using the method I described before.

It is all rather straightforward and mostly just removes the assumption that the local DHCP peer is the DHCP server, but I have not tested it against an actual relay agent.

**Comment by leahneukirchen** [comment]
Giving it a quick check, it seems to run fine now.  The "agent" MAC is determined immediately.
