### ISSUE TITLE
small manpage bugs

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#4]
`-l`, `--leasefile` doesn't exist anymore but is still in the manpage.

`-s`, `--state-dir` and `-t`, `--gw-metric` are not in the manpage.

There is a formatting error for the `-H` option and between `-H` and `-S`.

**Comment by niklata** [comment]
Nice catch!  I've fixed these errors and also corrected some cases where BR was used instead of BI for option entries.  Please let me know if I've missed anything.
