### ISSUE TITLE
error loop when using rfkill

### ISSUE THREAD

**Issue by leahneukirchen** [niklata/ndhc#5]
When rfkill is used (here, with a hardware switch), ndhc should consider the interface down (not sure how it can detect it gets up again, but it seems to "flap" from up -> down -> up when rfkill is toggled).

```
2015-02-13T10:16:38.38295 user.notice: ndhc: wlan0 hardware address a0:88:b4:a1:ce:50
2015-02-13T10:16:38.38309 user.notice: ndhc: wlan0: (rtnl_if_flags_send) netlink sendto returned NLMSG_ERROR: Operation not possible due to RF-kill
2015-02-13T10:16:38.38321 user.notice: ndhc: wlan0: (perform_ifup) Failed to set link to be up.
2015-02-13T10:16:38.38328 user.notice: ndhc: failed to set the interface to up state
```

p.s.: I hope you don't mind all the bugs I report, but I like ndhc a lot so far! You did a good job.

**Comment by niklata** [comment]
I think the obvious error here is that ndhc should detect the RF-kill NLMSG_ERROR and realize that the interface is down.  The questionable part is if there is a notification when the interface comes back when RF-kill is untoggled.  I'll read about RF-kill a bit and teach it to handle the NLMSG_ERROR.

Don't worry at all about reporting bugs in ndhc!  I'm very grateful for your patient and detailed reports.  I've tried to make ndhc production-quality, and these are all important bugs that need to be fixed.

**Comment by leahneukirchen** [comment]
Apparently you can poll on /dev/rfkill: http://git.kernel.org/cgit/linux/kernel/git/jberg/rfkill.git/tree/rfkill.c

**Comment by niklata** [comment]
Great find!  That looks suitable.  I'll check a bit to see if there's a netlink interface, too.  The only real advantage to netlink over a device node is that it's easier to set up the jail environment, though, so if there's no netlink equivalent, /dev/rfkill should work just fine.

**Comment by leahneukirchen** [comment]
stracing udev shows that it also should be reported on NETLINK_KOBJECT_UEVENT.

**Comment by niklata** [comment]
I think I'll go with the device file interface here.  The uevents (emitted by kernel driver core and usually consumed by udev) are documented as supported, too, but the rfkill dev interface seems simpler (streams binary structs) and netlink is almost always poorly documented and difficult/buggy to parse.

/usr/src/linux/Documentation/rfkill.txt has reasonable behavioral descriptions, too.

**Comment by niklata** [comment]
I've just committed a preliminary support for /dev/rfkill events.  For now, it requires the rfkill index to be manually specified via the --rfkill-idx option.  The rfkill devices can be found in /sys/class/rfkill/rfkill<IDX>.

It shouldn't require any changes to the chroot, as the device fd is opened at program start time before entering the jail.

ndhc should act as if the switch being hit is a hardware carrier loss/gain event if everything is working properly.  I think that's probably more correct than the switch acting as a user shutdown/reinit of the interface (the kill switch is disabling the phy layer, which is conceptually like pulling an ethernet cable), but it's possible that the behavior may need to be changed.

Please let me know how it works for you.  There should be event logging for rfkill events in general, so even if something fails, I should be able to work out what goes wrong.

**Comment by leahneukirchen** [comment]
```
wlan0 hardware address a0:88:b4:a1:ce:50
ndhc client 1.5 started on interface [wlan0].
epoll_add failed File exists
```

The epoll_add call tries to add the same socket fd twice to the eventpoll fd, but the /dev/rfkill is not added at all...

**Comment by niklata** [comment]
Ugh, it's just a bad typo.  Fixing it.

**Comment by niklata** [comment]
Should be corrected now.

**Comment by leahneukirchen** [comment]
Ok, activating rfkill during operation:

```
wlan0: Commands received and successfully executed.
wlan0: arp: Gateway hardware address d8:67:d9:6e:9b:42
wlan0: arp: DHCP agent hardware address d8:67:d9:6e:9b:42
rfkill: idx[1] type[1] op[2] soft[0] hard[1]
rfkill: radio now blocked; bringing interface down
wlan0: Carrier down.
rfkill: idx[0] type[2] op[2] soft[0] hard[1]
wlan0: Interface shut down.  Going to sleep.
wlan0: Resetting IP configuration.
wlan0: Sent to ifchd: 'ip4:0.0.0.0,255.255.255.255;'
wlan0: Interface IP set to: '0.0.0.0'
wlan0: Interface subnet set to: '255.255.255.255'
wlan0: (rtnl_if_flags_send) netlink sendto returned NLMSG_ERROR: Operation not possible due to RF-kill
wlan0: (perform_ip_subnet_bcast) Failed to set link to be up and running.
wlan0: Commands received and successfully executed.
wlan0: Interface is back.  Searching for new lease...
wlan0: Discovering DHCP servers...
wlan0: (send_dhcp_raw) sendto failed: Network is down
wlan0: Failed to send a discover request packet.
rfkill: idx[0] type[2] op[2] soft[1] hard[1]
rfkill: idx[1] type[1] op[2] soft[1] hard[1]
rfkill: radio now blocked; bringing interface down
wlan0: Carrier down.
rfkill: idx[11] type[2] op[2] soft[1] hard[0]
rfkill: idx[11] type[2] op[1] soft[1] hard[0]
wlan0: Discovering DHCP servers...
wlan0: (send_dhcp_raw) sendto failed: Network is down
wlan0: Failed to send a discover request packet.
wlan0: Discovering DHCP servers...
wlan0: (send_dhcp_raw) sendto failed: Network is down
wlan0: Failed to send a discover request packet.
```

According to "ip l", the link is indeed down, why does it try to send stuff?

Turning on again:

```
rfkill: idx[1] type[1] op[2] soft[1] hard[0]
rfkill: radio now blocked, but interface isn't up
rfkill: idx[0] type[2] op[2] soft[1] hard[0]
rfkill: idx[0] type[2] op[2] soft[0] hard[0]
rfkill: idx[1] type[1] op[2] soft[0] hard[0]
rfkill: radio now unblocked; bringing interface up
wlan0: Carrier down.
rfkill: idx[12] type[2] op[0] soft[0] hard[0]
wlan0: Discovering DHCP servers...
```

`3: wlan0: <NO-CARRIER,BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state DORMANT mode DORMANT group default qlen 1000`

Now it's stuck.  After restarting, picks up DHCP again...

**Comment by leahneukirchen** [comment]
When starting with rfkill active:

```
wlan0 hardware address a0:88:b4:a1:ce:50
wlan0: (rtnl_if_flags_send) netlink sendto returned NLMSG_ERROR: Operation not possible due to RF-kill
wlan0: (perform_ifup) Failed to set link to be up.
failed to set the interface to up state
```

and terminates.  IMO it should wait for the interface to come up.

**Comment by leahneukirchen** [comment]
BTW, I'm chris2 on freenode, /query me if you want less github ping pong.

**Comment by niklata** [comment]
Interface setting changes (via ifch) are now not assumed to always succeed (rfkill makes them fail).

Some of these errors will cause ndhc to terminate itself because the current state machine cannot be resumed at every possible error point where a retry would be necessary.  That means it's more important that ndhc run under some kind of process supervisor (such as perp, runit, s6, daemontools, etc).  ndhc always fell back on self-termination for severe errors, so this isn't really a new thing.

I probably will need to make the core logic be structured as a coroutine for optimal robustness.  Rather than directly dispatch actions from gathering DHCP/ARP replies, timeouts, carrier changes, and rfkill changes, a coroutine could act upon those notifications.  This would make it much easier to reason about the behavior and prove correctness.

**Comment by niklata** [comment]
The behavior here may also be changed with the coroutine rewrite; please see issue #6 for more information.  Please let me know if things have improved (or worsened).

**Comment by niklata** [comment]
The removal of carrier state tracking and switch to carrier poll-on-demand has likely removed these issues.  Please open a new bug things are still not right.
